### ISSUE TITLE
Update LL slides with up-to-date figures and texts

### ISSUE THREAD

**Issue by jdey4** [neurodata/talks#25]
Let's enumerate here all the changes we want to make in the slides: https://neurodata.io/talks/LL_2020Q2.html#59.

**Comment by jdey4** [comment]
-[ ] change the learning schema figure.

Simulation:
-[ ] update xor and nxor figure with white background and resource controlled result.
-[ ] include xor/nxor, xor/rxor and spiral experiment figures.
-[ ] Use 2-panel figure for both FTE and BTE in the case of resource growing and constrained considerations.

**Comment by levinwil** [comment]
(the below are in addition to Jayanta's changed)

- [ ] add Will to title slide and Acknowledgements, if appropriate

- [ ] on 'What is Lifelong Learning' slide, the first word should be "A" instead of "An"

- [ ] on 'What is Learning' slide, what is \mathcal{P}?

- [ ] on 'Has f Multitask Learned?' slide, \mathcal{E^~} is never used even though it is defined twice

- [ ] I'd get get rid of or replace the 'Graceful Forgetting', since that figure is really difficult to follow IMO 

- [ ] Replace CIFAR results fig with new results

**Comment by jovo** [comment]
i haven't looked through carefully, but anything you know is outdated, please remove.
and please make sure to add all the figures we have in our paper.

**Comment by alig1882** [comment]
- [ ] no more source data, rather replace the concept with side information
    - [ ] define side information, both intuitively and formally, with examples to elucidate both
    - [ ] make changes to places where source with mentioned and replace appropriately
- [ ] GTL no longer mentions strong and weak multitask learning, should we still mention in slides?
- [ ] meta learning not mentioned either in GTL
- [ ] change transformer to take in query space rather than \mathcal{X}, and correspondingly change transformed space from \tilde{\mathcal{X}} to \tilde{\mathcal{Q}}
- [ ] for composable hypotheses, representations are outputs of transformers, and posteriors are outputs of voters - so think name "Multitask ensemble representation learning" is off since we are aggregating output of voters also, not just representations.
- [ ] think in general we need to differentiate between posterior/predictive ensembling and representation ensembling and be careful with the naming accordingly.
- [ ] for composable hypotheses, when ensembling, operation is that decider and voter take in correspondingly the vector of voter and transformer outputs, not a union, right?
- [ ] introduce concepts of asymptotic transfer efficiency
- [ ] fundamental conjecture of transfer learning is no longer a conjecture because we have theorem 1 of GTL?
- [ ] specify what n_0 and n_1 are in the fundamental conjecture of transfer learning

**Comment by jovo** [comment]
@alig1882 
- i think to slim down slides we can move things that aren't in GTL to the "appendix".
- clevr is spelled right, do a google search, you can update the slide with a link to clarify
- please update all theory notations to use our current notation/definition set

thanks!
